# Generated by Django 5.0.6 on 2024-06-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='movies_images', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='box_office',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Кассовые сборы'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budgets',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Рейтинг'),
        ),
        migrations.AlterModelTable(
            name='movie',
            table='Фильмы',
        ),
    ]
