# Generated by Django 5.0.6 on 2024-07-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Комментарий',
        ),
    ]
