# Generated by Django 5.0.6 on 2024-07-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_comment_options_alter_comment_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
