# Generated by Django 5.0.6 on 2024-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_comment_options_alter_comment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_positive',
            field=models.BooleanField(blank=True, null=True, verbose_name='положительный'),
        ),
    ]
